- name: Play level Variables demo
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Variables from file
  hosts: localhost
  vars_files:
    - demo-var.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}