- name: Play level Variables demo
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Variables from file
  hosts: localhost
  vars_files:
    - demo-var.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Variables from tasks level
  hosts: localhost
  tasks:
   - name: Print variable
     ansible.builtin.debug:
        msg: URL = {{URL}}
     vars:
        URL: tasks.example.com

- name: Variables from Inventory file level
  hosts: localhost
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Facts
  hosts: localhost
  tasks:
    - name : Print hostname
      ansible.builtin.debug:
        msg : HOSTNAME = {{ansible_hostname}}, Memory ={{ansible_memory_mb.real.free}}
    - name: Print FQDN
      ansible.builtin.debug:
        msg: "{{ ansible_fqdn }}"
        # if any value starts with a variable then we need to quote it, Either single or double

- name : Register Variable
  hosts: localhost
  tasks :
     - name : run uptime command
       ansible.builtin.shell : uptime
       register : output
     - name : print output
       ansible.builtin.debug:
         msg: "{{output.stdout}}"
